/* Amplify Params - DO NOT EDIT
	API_HFHAPP_APPLICATIONTABLE_ARN
	API_HFHAPP_APPLICATIONTABLE_NAME
	API_HFHAPP_CONTACTFORMTABLE_ARN
	API_HFHAPP_CONTACTFORMTABLE_NAME
	API_HFHAPP_DEBTRECORDTABLE_ARN
	API_HFHAPP_DEBTRECORDTABLE_NAME
	API_HFHAPP_GRAPHQLAPIENDPOINTOUTPUT
	API_HFHAPP_GRAPHQLAPIIDOUTPUT
	API_HFHAPP_GRAPHQLAPIKEYOUTPUT
	API_HFHAPP_HABITATTABLE_ARN
	API_HFHAPP_HABITATTABLE_NAME
	API_HFHAPP_HOUSEHOLDMEMBERTABLE_ARN
	API_HFHAPP_HOUSEHOLDMEMBERTABLE_NAME
	API_HFHAPP_INCOMERECORDTABLE_ARN
	API_HFHAPP_INCOMERECORDTABLE_NAME
	API_HFHAPP_SAVINGRECORDTABLE_ARN
	API_HFHAPP_SAVINGRECORDTABLE_NAME
	API_HFHAPP_USERPROPSTABLE_ARN
	API_HFHAPP_USERPROPSTABLE_NAME
	ENV
	REGION
	STORAGE_S3HFHAPPSTORAGEBUCKET_BUCKETNAME
Amplify Params - DO NOT EDIT */

/**
 * @type {import('@types/aws-lambda').APIGatewayProxyHandler}
 */
exports.handler = event => {
  console.log(`EVENT: ${JSON.stringify(event)}`);
  for (const record of event.Records) {
    console.log(record.eventID);
    console.log(record.eventName);
    console.log('DynamoDB Record: %j', record.dynamodb);
  }
  return Promise.resolve('Successfully processed DynamoDB record');
};
