/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://omb6ahuy4jgsdcxel6mqrt43yi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-mjznmtntejbm3fapktrbwwdxvu",
    "aws_cloud_logic_custom": [
        {
            "name": "public",
            "endpoint": "https://pt6xwaf01l.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "sendEmailToApplicantAPI",
            "endpoint": "https://ab15jgie2i.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "userAPI",
            "endpoint": "https://uasiehcv0l.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "habitat",
            "endpoint": "https://6uvg6atj7e.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:4fdaf0e2-dc69-4756-898f-c63928352c59",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_NTw1oi5NG",
    "aws_user_pools_web_client_id": "67203j5kpoh72b11chus0kitr5",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "hfh-app-storage-bucket183905-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
