/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://7a5m3kr7srgjrgohwc2ntu566u.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5mejunhxonflln7d3n6lwkkgky",
    "aws_cloud_logic_custom": [
        {
            "name": "public",
            "endpoint": "https://pt6xwaf01l.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "sendEmailToApplicantAPI",
            "endpoint": "https://ezcqlkrlt3.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        },
        {
            "name": "userAPI",
            "endpoint": "https://j8f0ysunl3.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:775a799c-b880-4b85-910f-ae7a69182c58",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3zxo02ghK",
    "aws_user_pools_web_client_id": "4d6574ks6b0h37sr6g6dqsq280",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "hfh-app-storage-bucket160335-prod",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
