/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://mnd4jz6w6rfjvbzdgsatu6nejq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-i7gr36vcnjgbziweyk5fjvsoaa",
    "aws_cloud_logic_custom": [
        {
            "name": "public",
            "endpoint": "https://ibm7rzt8f9.execute-api.us-east-1.amazonaws.com/legacy",
            "region": "us-east-1"
        },
        {
            "name": "sendEmailToApplicantAPI",
            "endpoint": "https://xugytlrpri.execute-api.us-east-1.amazonaws.com/legacy",
            "region": "us-east-1"
        },
        {
            "name": "userAPI",
            "endpoint": "https://vdxnplvaxe.execute-api.us-east-1.amazonaws.com/legacy",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:0edeb284-0207-4330-ba2b-defb162b3e02",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_iaDkMXNlj",
    "aws_user_pools_web_client_id": "722scoui0pnkvluishdpgpgsjb",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "hfh-app-storage-bucket90853-legacy",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
